[package]
name = "valori-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "valori_ffi"
crate-type = ["cdylib"]

[dependencies]
valori-kernel = { path = "../" }
pyo3 = { version = "0.23", features = ["extension-module"] }
